In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import matplotlib.pyplot as plt 
%matplotlib inline 
# It will make plot output appear in the notebook as well as save in the notebook, hence next time when you open, you would be able to see the plot, without re running
plt.rc("font", size=14)
from sklearn.preprocessing import LabelEncoder # Just in case the output variable is in string form
lb = LabelEncoder() # Also if independent variables are in string format, encode those ones as well
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

In [2]:
data = pd.read_csv('online_shoppers_intention.csv')

In [3]:
data['Revenue'] = lb.fit_transform(data['Revenue'])
data['Month'] = lb.fit_transform(data['Month'])
data['VisitorType'] = lb.fit_transform(data['VisitorType'])

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Administrative           12330 non-null  int64  
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64  
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64  
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  int32  
 11  OperatingSystems         12330 non-null  int64  
 12  Browser                  12330 non-null  int64  
 13  Region                   12330 non-null  int64  
 14  TrafficType           

In [5]:
y = data['Revenue']
y

0        0
1        0
2        0
3        0
4        0
        ..
12325    0
12326    0
12327    0
12328    0
12329    0
Name: Revenue, Length: 12330, dtype: int64

In [6]:
x = data.drop(columns = ['Revenue'], inplace = True)


In [7]:
data

Administrative  Administrative_Duration  Informational  \
0                   0                      0.0              0   
1                   0                      0.0              0   
2                   0                      0.0              0   
3                   0                      0.0              0   
4                   0                      0.0              0   
...               ...                      ...            ...   
12325               3                    145.0              0   
12326               0                      0.0              0   
12327               0                      0.0              0   
12328               4                     75.0              0   
12329               0                      0.0              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                         0.0               1                 0.000000   
1                         0.0               2                64.000000   
2                         0.0               1                 0.000000   
3                         0.0               2                 2.666667   
4                         0.0              10               627.500000   
...                       ...             ...                      ...   
12325                     0.0              53              1783.791667   
12326                     0.0               5               465.750000   
12327                     0.0               6               184.250000   
12328                     0.0              15               346.000000   
12329                     0.0               3                21.250000   

       BounceRates  ExitRates  PageValues  SpecialDay  Month  \
0         0.200000   0.200000    0.000000         0.0      2   
1         0.000000   0.100000    0.000000         0.0      2   
2         0.200000   0.200000    0.000000         0.0      2   
3         0.050000   0.140000    0.000000         0.0      2   
4         0.020000   0.050000    0.000000         0.0      2   
...            ...        ...         ...         ...    ...   
12325     0.007143   0.029031   12.241717         0.0      1   
12326     0.000000   0.021333    0.000000         0.0      7   
12327     0.083333   0.086667    0.000000         0.0      7   
12328     0.000000   0.021053    0.000000         0.0      7   
12329     0.000000   0.066667    0.000000         0.0      7   

       OperatingSystems  Browser  Region  TrafficType  VisitorType  Weekend  
0                     1        1       1            1            2    False  
1                     2        2       1            2            2    False  
2                     4        1       9            3            2    False  
3                     3        2       2            4            2    False  
4                     3        3       1            4            2     True  
...                 ...      ...     ...          ...          ...      ...  
12325                 4        6       1            1            2     True  
12326                 3        2       1            8            2     True  
12327                 3        2       1           13            2     True  
12328                 2        2       3           11            2    False  
12329                 3        2       1            2            0     True  

[12330 rows x 17 columns]

In [8]:
x_train, x_test, y_train, y_test= train_test_split(data,y,test_size=0.3)

In [9]:
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(x_train)
xtest = sc_x.transform(x_test)

In [10]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\Users\Daksh Kapoor\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [11]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)

In [12]:
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[3037   75]
 [ 373  214]]


In [13]:
print ("Accuracy : ", accuracy_score(y_test, y_pred)*100)

Accuracy :  87.88861854555286


In [14]:
recall_score(y_test, y_pred, average=None)# Precision

array([0.97589974, 0.36456559])

In [15]:
precision_score(y_test, y_pred, average=None)

array([0.89061584, 0.74048443])

In [16]:
print(classification_report(y_test, y_pred))# You can print this one only, if needed.

              precision    recall  f1-score   support

           0       0.89      0.98      0.93      3112
           1       0.74      0.36      0.49       587

    accuracy                           0.88      3699
   macro avg       0.82      0.67      0.71      3699
weighted avg       0.87      0.88      0.86      3699

